### PR TITLE
Added new queries and new test cases

### PR DESCRIPTION
**Pull request by EssentiallyNoah**
Adds support for new queries taking advantage of the new features mentioned in #2 including:
- `get_multiple_works` - Fetching multiple works (uses new OR operator)
- `get_related_works` & `get_referenced_works` - Fetching referenced & related works
- `get_cited_by_works` - Fetching works citing the given work (uses cursor-based paging and lets user limit the number of results)

### CODE REVIEW

**Comment by dpriskorn** [comment]
Big thanks for this PR. I really like way you implemented the cursor and paging. Thanks for the tests also :)

**Comment by EssentiallyNoah** [comment]
@dpriskorn is there a good way to amend authorship on the PRs? The commit username is incorrect. I've amended the branches on my fork and can re-submit the PR, but am not sure if that would cleanly overwrite a PR that has already been merged.

**Comment by dpriskorn** [comment]
> @dpriskorn is there a good way to amend authorship on the PRs? The commit username is incorrect. I've amended the branches on my fork and can re-submit the PR, but am not sure if that would cleanly overwrite a PR that has already been merged.

I don't think so. What about we adopt the style of Guix and maintain a header in each file with copyrights with the name of all contributors?
Like so: 
'# Copyright 2022 Dennis Priskorn, x, y

**Comment by dpriskorn** [comment]
I went ahead and added a header to all files. Feel free to send a PR to add your name to the files you edited.

**Pull request merged**
